data:extend({
	{
		type = "recipe",
		name = "kr-hydrogen",
		category = "kr-atmosphere-condensation",
		icon = "__Krastorio2Assets__/icons/fluids/hydrogen.png",
		subgroup = "raw-material",
		order = "a[atmosphere-condensation]-a1[hydrogen]",
		enabled = false,
		always_show_made_in = true,
		always_show_products = true,
		hide_from_player_crafting = true,
		energy_required = 20,
		ingredients = {},
		results = {
			{ type = "fluid", name = "kr-hydrogen", amount = 30 },
		},
	},
	{
		type = "recipe",
		name = "kr-nitrogen",
		category = "kr-atmosphere-condensation",
		icon = "__Krastorio2Assets__/icons/fluids/nitrogen.png",
		subgroup = "raw-material",
		order = "a[atmosphere-condensation]-a3[nitrogen]",
		enabled = false,
		always_show_made_in = true,
		always_show_products = true,
		hide_from_player_crafting = true,
		energy_required = 30,
		ingredients = {},
		results = {
			{ type = "fluid", name = "kr-nitrogen", amount = 30 },
		},
	},
	{
		type = "recipe",
		name = "kr-oxygen",
		category = "kr-atmosphere-condensation",
		icon = "__Krastorio2Assets__/icons/fluids/oxygen.png",
		subgroup = "raw-material",
		order = "a[atmosphere-condensation]-a2[oxygen]",
		enabled = false,
		always_show_made_in = true,
		always_show_products = true,
		hide_from_player_crafting = true,
		energy_required = 5,
		surface_conditions = {
			{
				property = "pressure",
				min = 1000,
				max = 2000,
			},
		},
		ingredients = {},
		results = {
			{ type = "fluid", name = "kr-oxygen", amount = 30 },
		},
	},
})
