data:extend({
  {
    type = "recipe",
    -- This cannot have a kr- prefix because it needs to be grouped with the vanilla 'wood' item.
    name = "wood",
    enabled = false,
    category = "kr-growing",
    energy_required = 60,
    ingredients = {
      { type = "fluid", name = "water", amount = 200 },
    },
    results = {
      { type = "item", name = "wood", amount = 40 },
    },
    auto_recycle = false,
    main_product = "wood",
  },
  {
    type = "recipe",
    name = "kr-wood-with-fertilizer",
    icon = "__Krastorio2Assets__/icons/recipes/wood-with-fertilizer.png",
    subgroup = "raw-resource",
    order = "a[wood-with-fertilizer]",
    enabled = false,
    category = "kr-growing",
    energy_required = 60,
    ingredients = {
      { type = "fluid", name = "water", amount = 200 },
      { type = "item", name = "kr-fertilizer", amount = 1 },
    },
    results = {
      { type = "item", name = "wood", amount = 80 },
    },
    auto_recycle = false,
    main_product = "wood",
  },
  {
    type = "recipe",
    name = "kr-jellynut",
    localised_name = {"item-name.jellynut"},
    icon = "__space-age__/graphics/icons/jellynut.png",
    subgroup = "raw-resource",
    order = "b[jellynut]",
    enabled = false,
    category = "kr-growing",
    energy_required = 300,
    emissions_multiplier = 6,
    surface_conditions = { { property = "pressure", min = 2000, max = 2000 } },
    ingredients = {
      { type = "fluid", name = "water", amount = 3000 },
      { type = "item", name = "kr-fertilizer", amount = 3 },
      { type = "item", name = "jellynut-seed", amount = 6 },
    },
    results = {
      { type = "item", name = "jellynut", amount = 300 },
    },
    auto_recycle = false,
    main_product = "jellynut",
  },
  {
    type = "recipe",
    name = "kr-yumako",
    localised_name = {"item-name.yumako"},
    icon = "__space-age__/graphics/icons/yumako.png",
    subgroup = "raw-resource",
    order = "b[yumako]",
    enabled = false,
    category = "kr-growing",
    energy_required = 300,
    emissions_multiplier = 6,
    surface_conditions = { { property = "pressure", min = 2000, max = 2000 } },
    ingredients = {
      { type = "fluid", name = "water", amount = 3000 },
      { type = "item", name = "kr-fertilizer", amount = 3 },
      { type = "item", name = "yumako-seed", amount = 6 },
    },
    results = {
      { type = "item", name = "yumako", amount = 300 },
    },
    auto_recycle = false,
    main_product = "yumako",
  },
})
