data:extend({
  {
    type = "item",
    name = "kr-blank-tech-card",
    icon = "__Krastorio2Assets__/icons/items/blank-tech-card-1.png",
    subgroup = "science-pack",
    order = "a00[blank-tech-card]",
    stack_size = 200,
    weight = 1*kg,
  },
  {
    type = "item",
    name = "kr-biter-research-data",
    icon = "__Krastorio2Assets__/icons/cards/biters-research-data.png",
    subgroup = "science-pack",
    order = "a01[biters-research-data]",
    stack_size = 200,
    weight = 1*kg,
  },
  {
    type = "item",
    name = "kr-matter-research-data",
    icon = "__Krastorio2Assets__/icons/cards/matter-research-data.png",
    subgroup = "science-pack",
    order = "a02[matter-research-data]",
    stack_size = 200,
    weight = 1*kg,
  },
  {
    type = "item",
    name = "kr-space-research-data",
    icon = "__Krastorio2Assets__/icons/cards/space-research-data.png",
    subgroup = "science-pack",
    order = "a03[space-research-data]",
    stack_size = 1000,
    weight = 1*kg,
  },
  {
    type = "item",
    name = "kr-electromagnetic-research-data",
    icon = "__Krastorio2-spaced-out__/graphics/icons/electromagnetic-research-data.png",
    subgroup = "science-pack",
    order = "a04[electromagnetic-research-data]",
    stack_size = 200,
    weight = 1*kg,
  },
  {
    type = "item",
    name = "kr-metallurgic-research-data",
    icon = "__Krastorio2-spaced-out__/graphics/icons/metallurgic-research-data.png",
    subgroup = "science-pack",
    order = "a06[metallurgic-research-data]",
    stack_size = 200,
    weight = 1*kg,
  },
  {
    type = "item",
    name = "kr-agricultural-research-data",
    icon = "__Krastorio2-spaced-out__/graphics/icons/agricultural-research-data.png",
    subgroup = "science-pack",
    order = "a07[agricultural-research-data]",
    stack_size = 200,
    weight = 1*kg,
    spoil_result = "spoilage",
    spoil_ticks = 54000
  },
  {
    type = "item",
    name = "kr-cryogenic-research-data",
    icon = "__Krastorio2-spaced-out__/graphics/icons/cryogenic-research-data.png",
    subgroup = "science-pack",
    order = "a08[cryogenic-research-data]",
    stack_size = 200,
    weight = 1*kg,
  },
  {
    type = "item",
    name = "kr-promethium-research-data",
    icon = "__Krastorio2-spaced-out__/graphics/icons/promethium-research-data.png",
    subgroup = "science-pack",
    order = "a09[promethium-research-data]",
    stack_size = 200,
    weight = 1*kg,
  },
  {
    type = "tool",
    name = "kr-matter-tech-card",
    localised_description = { "item-description.science-pack" },
    icon = "__Krastorio2Assets__/icons/cards/matter-tech-card.png",
    subgroup = "science-pack",
    order = "b09[matter-tech-card]",
    stack_size = 200,
    weight = 1*kg,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value",
    pictures = {
      layers = {
        {
          filename = "__Krastorio2Assets__/icons/cards/matter-tech-card.png",
          size = 64,
          scale = 0.5,
        },
        {
          filename = "__Krastorio2Assets__/icons/cards/matter-tech-card-light.png",
          size = 64,
          scale = 0.5,
          draw_as_light = true,
          flags = { "light" },
        },
      },
    },
  },
  {
    type = "tool",
    name = "kr-advanced-tech-card",
    localised_description = { "item-description.science-pack" },
    icon = "__Krastorio2Assets__/icons/cards/advanced-tech-card.png",
    subgroup = "science-pack",
    order = "b10[advanced-tech-card]",
    stack_size = 200,
    weight = 1*kg,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value",
    pictures = {
      layers = {
        {
          filename = "__Krastorio2Assets__/icons/cards/advanced-tech-card.png",
          size = 64,
          scale = 0.5,
        },
        {
          filename = "__Krastorio2Assets__/icons/cards/advanced-tech-card-light.png",
          size = 64,
          scale = 0.5,
          draw_as_light = true,
          flags = { "light" },
        },
      },
    },
  },
  {
    type = "tool",
    name = "kr-singularity-tech-card",
    localised_description = { "item-description.science-pack" },
    icon = "__Krastorio2Assets__/icons/cards/singularity-tech-card.png",
    subgroup = "science-pack",
    order = "b11[singularity-tech-card]",
    stack_size = 200,
    weight = 1*kg,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value",
    pictures = {
      layers = {
        {
          filename = "__Krastorio2Assets__/icons/cards/singularity-tech-card.png",
          size = 64,
          scale = 0.5,
        },
        {
          filename = "__Krastorio2Assets__/icons/cards/singularity-tech-card-light.png",
          size = 64,
          scale = 0.5,
          draw_as_light = true,
          flags = { "light" },
        },
      },
    },
  },
})
